-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CONTEM(
id_produto int,
id_pedido int,
id_contem int auto_increment primary key PRIMARY KEY
);

CREATE TABLE ENTREGA (
id_delivery int ,
id_funcionario int ,
id_entrega int auto_increment primary key PRIMARY KEY
);

CREATE TABLE REALIZA (
Id_cliente int ,
id_pedido int ,
id_realiza int auto_increment primary key PRIMARY KEY
);

CREATE TABLE ATENDE (
id_funcionario int ,
id_pedido int ,
id_atende int auto_increment primary key PRIMARY KEY
);

CREATE TABLE CONSOME (
id_insumo int,
id_produto int,
id_consome int auto_increment primary key PRIMARY KEY
);

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL varchar(35) not null,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
DESCONTO DECIMAL(5,2) DEFAULT 0.00,
DESCRICAO VARCHAR(200),
STATUS_CATEGORIA ENUM('ATIVO','INATIVO') NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CARGO VARCHAR(35) NOT NULL,
SALARIO DECIMAL(5,2),
CPF varchar(14) not null,
DATA_ADMISSAO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
    ID_INSUMO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_INSUMO VARCHAR(35) NOT NULL,
    QUANTIDADE_MINIMA INT NOT NULL,
    QUANTIDADE_ATUAL INT NOT NULL,
    UNIDADE_MEDIDA ENUM('KG', 'ML', 'UN') NOT NULL
);

CREATE TABLE IF NOT EXISTS PROGRAMA_FIDELIDADE (
    ID_FIDELIDADE INT AUTO_INCREMENT PRIMARY KEY,
    DATA_EXPIRACAO_PONTOS DATE NOT NULL,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCONTO DECIMAL(5,2) DEFAULT 0.00,
    SALDO_PONTOS INT NOT NULL,
    NIVEL_CLIENTE VARCHAR(35) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_TOTAL DECIMAL(5,2),
    OBSERVACAO VARCHAR(200),
    STATUS_PEDIDO ENUM('ATIVO', 'INATIVO'),
    TIPO_PEDIDO ENUM('PRESENCIAL', 'DELIVERY'),
    DATA_HORA timestamp default current_timestamp
);

CREATE TABLE IF NOT EXISTS PAGAMENTO (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY_KEY,
    FORMA_PAGAMENTO ENUM('DINHEIRO', 'PIX', 'CARTAO'),
    DATA_HORA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR_PAGO DECIMAL(5,2),
    STATUS_PAGAMENTO VARCHAR(35) NOT NULL,
    DESCONTO DECIMAL(1,2)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    PRECO_UNITARIO DECIMAL(5,2),
    CATEGORIA VARCHAR(35) NOT NULL,
    DESCRICAO VARCHAR(200),
    NOME VARCHAR(20) NOT NULL,
    PESO FLOAT
);

CREATE TABLE IF NOT EXISTS DELIVERY (
    ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
    DATA_HORA_SAIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_ENTREGA VARCHAR(30),
    TAXA_ENTREGA DECIMAL(1,2),
    ENDERECO_ENTREGA VARCHAR(35) NOT NULL,
    NOME_ENTREGADOR VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(70),
    TELEFONE VARCHAR(20),
    NOME VARCHAR(60),
    CNPJ CHAR(14),
    ENDERECO VARCHAR(100)
);


