-- Comandos para criar BD
-- 1
CREATE DATABASE CLINICA_MEDICA_KEYNAN;
CREATE DATABASE IF NOT EXISTS CLINICA_MEDICA_KEYNAN;
CREATE DATABASE BANCO_DADOS;

-- ATIVAR BD E ATUALIZAR SCHEMAS
-- 2
USE CLINICA_MEDICA_KEYNAN;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS PACIENTES (
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
CONVENIO ENUM ('SIM', 'NAO') NOT NULL  
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
SALARIO DECIMAL(5,2) DEFAULT 0.00
);

-- ALTERAR INFORMAÇÕES DA TABELA
-- ALTER TABLE
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100) NOT NULL;  

-- ALTERAR TIPO DE DADOS DE CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOSS; 

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE FUNCIONARIOSS;

-- APAGAR BD
DROP DATABASE CLINICA_MEDICA_KEYNAN;

-- APAGAR TABELAS 
DROP TABLES FUNCIONARIOSS;

-- MOSTRAR TABELAS NO BD
SHOW TABLES;

-- MOSTRAR TODOS OS BD
SHOW DATABASES;

-- INSERIR DADOS NO BD
INSERT INTO FUNCIONARIOSS (ID_FUNCIONARIO,NOME_FUNCIONARIO,CPF,TELEFONE,SALARIO)
VALUES (2,'LIVIA','124.478.854-13','(19)98103-0501','999'),
(3,'LUCCAS','251.123.456-78','(11)91239-8123','300');

INSERT INTO PACIENTES (ID_PACIENTE,NOME_PACIENTE,CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUES(DEFAULT, 'BRUNO','130.456.789-12','1983-10-23','BRUNO@SENAI.BR','(12) 1234 4678', DEFAULT),
(DEFAULT, 'LUANA','251.999.908-99','2010-06-21','LUANA@SENAI.BR','(19) 9543 8764', DEFAULT);
-- PADRÃO PARA DATA ANO-MÊS-DIA


-- CONSULTAR DADOS NO BD
SELECT * FROM FUNCIONARIOSS, PACIENTES;







