-- PROJETO SMARTCOFFEE_LUANA

-- CRIAR BANCO DE DADOS
-- ATIVAR BANCO DE DADOS
-- CRIAR TABELAS

CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_LUANA;
USE SMARTCOFFEE_LUANA;

CREATE TABLE IF NOT EXISTS PEDIDOS (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
OBSERVACAO VARCHAR(200),
DATA_PEDIDO DATE NOT NULL,
VALOR_TOTAL DECIMAL(5,2) DEFAULT 0.00,
TIPO_PEDIDO VARCHAR(35) NOT NULL,
STATUS_PEDIDO ENUM ('ATIVO', 'INATIVO') NOT NULL  
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGO DECIMAL(5,2) DEFAULT 0.00,
STATUS_PAGAMENTO VARCHAR(35) NOT NULL,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX') NOT NULL,
DESCONTO DECIMAL (2,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS DELIVERY (
ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
STATUS_ENTREGA VARCHAR(30) NOT NULL,
ENDERECO_ENTREGA VARCHAR(35) NOT NULL,
TAXA_ENTREGA DECIMAL (2,2) DEFAULT 0.00,
HORA_ENTREGA DATE NOT NULL,
NOME_ENTREGADOR VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
ID_PRODUTO INT auto_increment PRIMARY KEY,
CATEGORIA VARCHAR(35) NOT NULL,
NOME VARCHAR(60) NOT NULL,
PRECO DECIMAL (5,2) DEFAULT 0.00,
PESO DECIMAL (4,2) NOT NULL,
DESCRICAO VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(15),
NOME VARCHAR(60) NOT NULL,
CNPJ VARCHAR(14),
ENDERECO VARCHAR(60)
);

-- OPCIONAIS NO DIA 21/08/2026
-- INSERIR DADOS
-- CONSULTAR DADOS