-- COMANDO PARA CRIAR UM BANCO DE DADOS
CREATE DATABASE ESCOLA_LUANA;
CREATE DATABASE ESCOLA_LUANA2;

-- COMANDO PARA APAGAR UM BANCO DE DADOS
DROP DATABASE escola_luana2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE ESCOLA_LUANA;

-- CRIAR TABELAS
CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
STATUS_ALUNO CHAR(10) DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FUNCIONARIOS(
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE DISCIPLINA(
ID_DISCIPLINA INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SEMESTRE VARCHAR(30) NOT NULL,
CARGA_HORARIA INT auto_increment,
PROFESSOR_RESPONSAVEL VARCHAR(50) NOT NULL,
TIPO_AVALIACAO CHAR(15) DEFAULT "FORMATIVA"
);

CREATE TABLE TURMA(
ID_TURMA INT AUTO_INCREMENT PRIMARY KEY,
SERIE VARCHAR(10) NOT NULL,
NUM_TURMA INT AUTO_INCREMENT,
TURNO VARCHAR(20) NOT NULL,
CAPACIDADE INT auto_increment,
SALA INT auto_increment
);
