-- Active: 1788519232579@@127.0.0.1@3306@smartcoffee_dml_luana
DROP DATABASE IF EXISTS SMARTCOFFEE_DML_LUANA;

CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_DML_LUANA;

USE SMARTCOFFEE_DML_LUANA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) UNIQUE,
    TELEFONE VARCHAR(15),
    CIDADE VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ABERTO','PREPARANDO','FINALIZANDO','CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(150),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO(
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_PAGAMENTO_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

-- INSERINDO DADOS NO BD
INSERT INTO cliente (nome,email,telefone,cidade,ativo) VALUES
('Livia Stein', 'livia@email.com','1999999000','Limeira',TRUE),
('Arthur Nunes','arthur@email.com','1999999901','Rondonia',TRUE),
('Beatriz Raissa','beatriz@email.com','1999999902','Limeira',TRUE),
('Dandara Dias', 'dandara@email.com','1998230450','Limeira',TRUE),
('Davi Ferreira','davi@email.com',NULL,'Limeira',TRUE),
('Felipe Rodrigues','felipe@email.com',NULL,'Limeira',TRUE),
('Francisco Magri','chico@email.com','1999999903','Limeira',TRUE),
('Franz Kramer','franz@email.com','1999999904','Limeira',TRUE),
('Gabriel Nogueira','gabriel@email.com','1999999905','Limeira',TRUE),
('Gabrielli Araujo','gabrielli@email.com','1999999906','Americana',TRUE),
('Isabella Alves','isabella@email.com',NULL,'Limeira',TRUE),
('Keynan Santos','keynan@email.com','1999999907','Santos',TRUE),
('Larissa Ramires','larissa@email.com','1999999908','Limeira',TRUE),
('Leonardo Dias','leonardo@email.com','1999999909','Valinhos',TRUE),
('Luana Lima','luana@email.com','1999999910','Limeira',TRUE),
('Luccas Manfredi','lucas@email.com','1999999911','Campinas',TRUE);

INSERT INTO CATEGORIA (NOME) VALUES('Cafés'),('Bebidas Geladas'),('Bebidas Quentes'),('Salgados'),('Sobremesas'),('Combo');

INSERT INTO CATEGORIA (NOME) VALUES
('DOCES');

INSERT INTO PRODUTO (NOME,PRECO,ATIVO,ID_CATEGORIA) VALUES
('Café Tradicional',7.00,TRUE,1), ('Bolo',50.00,TRUE,19), ('Milk-Shake',12.00,TRUE,2), ('Chá',7.00,TRUE,3), ('Misto quente',10.00,TRUE,4);

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS, VALOR_TOTAL, ID_CLIENTE) VALUES (NOW(),
'FINALIZADO', 0.00, 17);

INSERT INTO forma_pagamento (DESCRICAO) VALUES
('PIX'),('DÉBITO'),('CRÉDITO'),('DINHEIRO'),('CARTAO ALIMENTAÇÃO');

-------------------------------------------------------------
-- ATRIBUIR NOMES AOS IDS
INSERT INTO CATEGORIA (NOME) VALUES 
('Combos Extras');

SET @categorias_voas = (SELECT NOME FROM CATEGORIA WHERE NOME = 'Combos Extras');

SELECT @categorias_novas;

INSERT INTO 
SET @CATEGORIA = LAST_INSERT_ID();
SELECT @CATEGORIA;
-----------------------------------------
SELECT * FROM CATEGORIA;
SELECT * FROM PEDIDO;

-- ATUALIZANDO OU MODIFICANDO DADOS NO BD
-- LEMBRAR DE SEMPRE EXECUTAR O SELECT PARA ATUALIZAR (UPDATE)
-- E NUNCA JAMAIS NEVER FAÇA UM UPDATE SEM WHERE 
-- EX 1: MODIFICANDO VALORES INDIVIDUAIS
UPDATE cliente
SET TELEFONE = '1988880001'
WHERE ID_CLIENTE = 9

UPDATE cliente
SET TELEFONE = '0000000000'


-- EX 2: MODIFICANDO VÁRIOS VALORES
UPDATE CLIENTE
SET TELEFONE = '1999999901',
    CIDADE = 'PIRACICABA'
WHERE ID_CLIENTE = 9;


--APAGAR DADOS DA TABELA NO BD
DELETE FROM cliente
WHERE ID_CLIENTE = 9;


-- CONSULTAR DADOS NO BD
SELECT * FROM CLIENTE
WHERE ID_CLIENTE = 9;

SELECT * FROM CATEGORIA;

--PROCEDIMENTO DE UMA COMPRA
--PASSO 1: REALIZAR CADASTRO CLIENTE

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CIDADE,ATIVO) VALUES ('Carlos Silva', 'carlos.silva3@email.com', '19999999999','Santos',TRUE);
SET @cliente_compra = LAST_INSERT_ID();

-- PASSO 2: REALIZAR PEDIDO
INSERT INTO PEDIDO(DATA_PEDIDO,STATUS_PEDIDO,VALOR_TOTAL,ID_CLIENTE) VALUES 
(NOW(),'ABERTO',0.00,@cliente_compra);
SET @pedido_compra = LAST_INSERT_ID();

-- PASSO 3: INSERINDO ITENS
INSERT INTO item_pedido (ID_PEDIDO, id_produto, quantidade, preco_unitario) VALUES
(@pedido_compra,4,1,13.00), (@pedido_compra,3,1,9.00);

--PASSO 4 - ATUALIZANDO TOTAL E STATUS
UPDATE pedido
SET VALOR_TOTAL = 22.00,
    STATUS_PEDIDO = 'preparando'
WHERE id_pedido = @pedido_compra;

-- PASSO 5 - REGISTRAR PAGAMENTO
INSERT INTO pagamento (id_pedido,id_forma_pagamento,valor,data_pagamento) VALUES
(@pedido_compra,2,22.00,NOW());

--  PASSO 6 - CONSULTAR PEDIDO E RESULTADO
SELECT P.ID_PEDIDO,
    c.nome AS Nome_Cliente,
    p.status_pedido AS Status_Pedido,
    p.valor_total AS Compra_Total
FROM pedido p 
JOIN cliente c ON c.id_cliente = p.id_cliente 
WHERE p.id_pedido = @pedido_compra;

-- TRANSAÇÕES - SEGURANÇA PARA DML
START TRANSACTION;
UPDATE produto
SET preco = preco * 2.80
WHERE id_categoria = 1;

SELECT id_produto, nome, preco
FROM produto
WHERE id_categoria = 1;
-- DESFAZ O QUE FIZEMOS ERRADO OU VOLTA UMA TRANSAÇÃO
ROLLBACK;
-- VALIDA O PROCEDIMENTO DE TRANSAÇÃO
COMMIT;

START TRANSACTION;
UPDATE cLIENTE set CIDADE = 'Santos' WHERE id_cliente = 121;
SELECT * FROM cliente WHERE id_cliente = 121;
COMMIT;
ROLLBACK;