CREATE DATABASE IF NOT EXISTS OFICINA_LUANA;
USE OFICINA_LUANA;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL,
DATA_CADASTRO timestamp default current_timestamp,
EMAIL VARCHAR(70),
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(11) NOT NULL  
);

CREATE TABLE IF NOT EXISTS VEICULOS (
ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
CAPACIDADE INT,
PRECO DECIMAL(7,2) NOT NULL,
TIPO_VEICULO VARCHAR(30) NOT NULL,
MARCA VARCHAR(20) NOT NULL,
STATUS_VEICULOS ENUM ('VENDIDO', 'NAO VENDIDO') NOT NULL  
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
SALARIO DECIMAL(5,2) DEFAULT 0.00,
TELEFONE VARCHAR(11) NOT NULL,
CARGO VARCHAR(30) NOT NULL,
DATA_ADMISSAO DATE NOT NULL  
);

CREATE TABLE IF NOT EXISTS MODELOS (
ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
ANO_LANCAMENTO DATE NOT NULL,
PESO CHAR(20) DEFAULT 0.00,
FABRICANTE VARCHAR(60) NOT NULL,
TIPO_MODELO VARCHAR (30) 
);

CREATE TABLE IF NOT EXISTS MARCAS (
ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
FABRICANTE VARCHAR(60),
TIPO_PRODUTO VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(35) NOT NULL,
ANO_LANCAMENTO DATE NOT NULL  
);

CREATE TABLE IF NOT EXISTS SERVICOS (
ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
FUNCIONARIO_RESPONSAVEL VARCHAR(60) NOT NULL,
DATA_SERVICO DATE NOT NULL,
PRECO DECIMAL(5,2) DEFAULT 0.00,
TEMPO_ESTIMADO VARCHAR(20) NOT NULL,
TIPO_SERVICO VARCHAR(100) NOT NULL  
);

CREATE TABLE IF NOT EXISTS PECAS (
ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
PESO CHAR(10),
PRECO DECIMAL(5,2) DEFAULT 0.00,
FABRICANTE VARCHAR(60),
DATA_CADASTRO timestamp default current_timestamp  
);

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVICO(
ID_ORDEM_DE_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
DATA_ORDEM DATE NOT NULL,
VEICULO VARCHAR(30) NOT NULL,
TEMPO_ESTIMADO VARCHAR(20) NOT NULL,
VALOR_TOTAL DECIMAL(5,2) NOT NULL 
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
VALOR_PAGO DECIMAL(8,2) DEFAULT 0.00,
STATUS_PAGAMENTO VARCHAR(30),
DESCONTO DECIMAL(2,2) DEFAULT 0.00,
FORMA_PAGAMENTO ENUM ('CREDITO', 'DEBITO', 'DINHEIRO') NOT NULL,
DATA_PAGAMENTO timestamp default current_timestamp  
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
CNPJ CHAR(14),
TELEFONE VARCHAR(11) NOT NULL,
EMAIL VARCHAR(35),
NOME VARCHAR(60) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL  
);

ALTER TABLE CLIENTES ADD ITEM_COMPRADO VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES DROP COLUMN ITEM_COMPRADO;

ALTER TABLE VEICULOS ADD LOCAL_FABRICADO VARCHAR(100) NOT NULL;
ALTER TABLE VEICULOS DROP COLUMN LOCAL_FABRICADO;

ALTER TABLE MARCAS ADD LOCAL_ORIGEM VARCHAR(100) NOT NULL;
ALTER TABLE MARCAS DROP COLUMN LOCAL_ORIGEM;

ALTER TABLE MODELOS ADD PRECO DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE MODELOS DROP COLUMN PRECO;

ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100) NOT NULL;
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

ALTER TABLE SERVICOS ADD OBSERVACOES VARCHAR(100);
ALTER TABLE SERVICOS DROP COLUMN OBSERVACOES;

ALTER TABLE PECAS ADD QUANTIDADE DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE PECAS DROP COLUMN QUALIDADE;

ALTER TABLE ORDEM_DE_SERVICO ADD OBSERVACAO VARCHAR(100);
ALTER TABLE ORDEM_DE_SERVICO DROP COLUMN OBSERVACAO;

ALTER TABLE PAGAMENTOS ADD STATUS_PAGAMENTO ENUM ('PAGO', 'NÃO PAGO') NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN STATUS_PAGAMENTO;

ALTER TABLE FORNECEDORES ADD PECA_FORNECIDA VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDORES DROP COLUMN PECA_FORNECIDA;

RENAME TABLE MODELOS TO MODELOS_FAB; 







